"undefined"!=typeof jQuery&&function(e){var t={xdomain:"*",ie:navigator.userAgent.toLowerCase().indexOf("msie")>-1,scrollToTop:!0},n={init:function(){return this.each(function(n){var i=e(this)
window.postMessage?window.addEventListener?window.addEventListener("message",function(e){o.messageHandler(i,e)},!1):window.attachEvent&&window.attachEvent("onmessage",function(e){o.messageHandler(i,e)},i):setInterval(function(){var e=window.location.hash.match(/^#h(\d+)(s?)$/)
e&&(o.setHeight(i,e[1]),t.scrollToTop&&"s"===e[2]&&scroll(0,0))},150)})}},o={messageHandler:function(e,n){var i,a,s
if("*"!==t.xdomain){var r=new RegExp(t.xdomain+"$")
if("null"==n.origin)throw new Error("messageHandler( elem, e): There is no origin.  You are viewing the page from your file system.  Please run through a web server.")
if(!n.origin.match(r))throw new Error("messageHandler( elem, e): The orgin doesn't match the responsiveiframe  xdomain.")
s=!0}if(("*"===t.xdomain||s)&&(a=(n.data+"").match(/^(\d+)(s?)$/))&&3===a.length){if(i=parseInt(a[1],10),!isNaN(i))try{o.setHeight(e,i)}catch(e){}t.scrollToTop&&"s"===a[2]&&scroll(0,0)}},setHeight:function(e,t){e.css("height",t+"px")},getDocHeight:function(){var e=document
return Math.min(Math.max(e.body.scrollHeight,e.documentElement.scrollHeight),Math.max(e.body.offsetHeight,e.documentElement.offsetHeight),Math.max(e.body.clientHeight,e.documentElement.clientHeight))}}
e.fn.responsiveIframe=function(o){return n[o]?n[o].apply(this,Array.prototype.slice.call(arguments,1)):"object"!=typeof o&&o?void e.error("Method "+o+" does not exist on jQuery.responsiveIframe"):(e.extend(t,arguments[0]),n.init.apply(this))}}(jQuery),function(){var e,t=function(){e=this}
function n(){return new t}t.prototype.allowResponsiveEmbedding=function(){window.addEventListener?(window.addEventListener("load",e.messageParent,!1),window.addEventListener("resize",e.messageParent,!1)):window.attachEvent&&(window.attachEvent("onload",e.messageParent),window.attachEvent("onresize",e.messageParent))},t.prototype.messageParent=function(e){var t=document.body.offsetHeight
t=e?t+"s":t,parent.postMessage?parent.postMessage(t,"*"):window.location.hash="h"+t},"undefined"==typeof exports?window.responsiveIframe=n:(void 0).exports.responsiveIframe=n}()
