function show_selector(e){"use strict"
$("#"+e+" .commune-selector").removeClass("required"),$("#"+e+" .commune-selector").show()}function select_commune(e,t,c,i){"use strict"
$("#"+i+" .commune-current").remove()
var o=$('label[for="'+e+'"]').html()
$("#"+i+" .commune-widget").before('<div class="commune-current" aria-live="polite">'+o+' <a href="#'+i+'" onclick="show_selector(\''+i+"');\">"+t+'</a> <a href="#'+i+'" onclick="clear_selection(\''+i+"');\">"+c+"</a></div>"),$("#"+i+" #"+e).attr("checked","checked"),$("#"+i+" .commune-selector").hide(),$("#"+i+" .commune-list").hide(),$("body").scrollTop(0)}function clear_selection(e){"use strict"
$("#"+e+" .commune-current").remove(),$("#"+e+" input:checked").removeAttr("checked"),show_selector(e)}function renderCommuneSelector(e,t,c,i,o){"use strict"
$("#"+i+" .commune-list div").css("display","none"),$(document).on("click","#"+i+" .commune-selector a",function(t){$("#"+i+" .commune-list").show(),$("#"+i+" .commune-list div").css("display","none"),$("#"+i+" .commune-list div").attr("aria-hidden","true"),$("#"+e+"-list-"+$(this).html()).css("display","block"),$("#"+e+"-list-"+$(this).html()).attr("aria-hidden","false")}),$("#"+i+" .commune-list input").hide()
for(var l,r,a='<div class="abc commune-selector '+o+'" role="tablist"><ul>',n="ABCDEFGHIJKLMNOPQRSTUVWXYZ",s=0;s<n.length;s++)l=n.charAt(s),a+="<li>",a+=(r=$("#"+e+"-list-"+l).size()>0)?'<a role="tab" id="aria-tab-'+l+'" href="#'+e+"-list-"+l+'">':"<span>",a+=l,a+=r?"</a>":"</span>",a+="</li>"
a+="</ul></div>",$("#"+i+" .commune-widget").prepend(a),$("#"+i+" .commune-list label").each(function(){$(this).wrap('<a href="#" onclick="select_commune(\''+$(this).attr("for")+"','"+t+"', '"+c+"', '"+i+"'); return false\"></a>")}),$('input[name="'+e+'"]:checked').attr("id")&&select_commune($('input[name="'+e+'"]:checked').attr("id"),t,c,i),$("#"+i+" .commune-widget").attr("role","tabpanel"),$("#"+i+" .commune-widget").attr("aria-live","polite"),$("#"+i+" .commune-list").attr("aria-live","polite"),$("#"+i+" .commune-list div").attr("role","tabpanel"),$("#"+i+" .commune-list div").each(function(){var t=$(this).attr("id").match(/[A-Z]{1}/)
$("#"+e+"-list-"+t).attr("aria-labelledby","aria-tab-"+t)})}